POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "testi",
    "author": "tester",
    "url": "www.google.com",
    "likes": 7,
    "userId": "5f8ed1cf9dafb939c80edc64"
}